<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AspectInjector_Enabled>false</AspectInjector_Enabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="xunit" Version="2.5.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\src\AspectInjector.Analyzer\AspectInjector.Analyzer.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Fixers\" />
  </ItemGroup>

</Project>
