<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FluentIL.Common\FluentIL.Common.csproj" />
    <ProjectReference Include="..\AspectInjector.Broker\AspectInjector.Broker.csproj" />
  </ItemGroup>
</Project>
